### ISSUE TITLE
Wheel files for python 3.13

### ISSUE THREAD

**Issue by vmeurisse** [wiktor-k/pysequoia#33]
Hello,

The latest version of PySequoia doesn't have wheel files for python 3.13 on pypi.
https://pypi.org/project/pysequoia/0.1.24/#files

Would it be possible to add them as it makes the installation of the package much simpler?

Regards

**Comment by wiktor-k** [comment]
Hi 👋 

Yep, I'll take a look at it. It's a valid concern. 

Thanks for reporting!

**Comment by wiktor-k** [comment]
I've updated all deps, including build tools and I see they build for Python 3.13: https://pypi.org/project/pysequoia/#files

I consider this issue closed but please do test if everything checks out and re-open if there are problems.

See you! :wave:
